# Default database configuration

development:
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  password:
  database: darius_development

test:
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  password:
  database: darius_test

production:
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  password:
  database: darius_production

cucumber:
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  password:
  database: darius_cuke
